import React,{useEffect,useState} from 'react';
import { apiRequest } from '../utils/api.js';
import { AlertBox } from './ui/ExecutiveUI.jsx';

const VAZIO={nome:'',cpf:'',titulo_eleitor:'',data_nascimento:'',telefone:'',whatsapp:'',email:'',endereco:'',bairro:'',cidade:'',uf:'',cep:'',zona_eleitoral:'',secao_eleitoral:'',status_voto:'nao_identificado',observacoes:''};
export default function EleitorFormModal({eleitor,onFechar,onSalvo,podeExcluir}){
 const [form,setForm]=useState(VAZIO);const [erro,setErro]=useState('');const [salvando,setSalvando]=useState(false);
 useEffect(function(){setForm(eleitor?{...VAZIO,...eleitor,data_nascimento:eleitor.data_nascimento?String(eleitor.data_nascimento).slice(0,10):''}:VAZIO);},[eleitor]);
 function campo(nome){return {value:form[nome]??'',onChange:e=>setForm({...form,[nome]:e.target.value})};}
 async function salvar(e){e.preventDefault();setSalvando(true);setErro('');try{const corpo={...form};if(String(corpo.cpf).includes('*'))delete corpo.cpf;await apiRequest(eleitor?'/voters/'+eleitor.id:'/voters',{method:eleitor?'PUT':'POST',body:JSON.stringify(corpo)});onSalvo();}catch(err){setErro(err.message);}finally{setSalvando(false);}}
 async function excluir(){if(!window.confirm('Excluir este eleitor? Esta ação não pode ser desfeita.'))return;try{await apiRequest('/voters/'+eleitor.id,{method:'DELETE'});onSalvo();}catch(err){setErro(err.message);}}
 return <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" role="dialog" aria-modal="true"><form onSubmit={salvar} className="bg-white rounded-xl shadow-xl w-full max-w-3xl max-h-[90vh] overflow-y-auto p-6"><div className="flex justify-between mb-5"><div><h2 className="text-lg font-semibold">{eleitor?'Editar eleitor':'Novo eleitor'}</h2><p className="text-xs text-slate-500">Preencha apenas dados necessários e autorizados.</p></div><button type="button" onClick={onFechar} aria-label="Fechar">✕</button></div>{erro&&<AlertBox tipo="erro">{erro}</AlertBox>}
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3"><div className="sm:col-span-2"><label className="label">Nome</label><input className="input" {...campo('nome')} required /></div><div><label className="label">CPF</label><input className="input" {...campo('cpf')} /></div><div><label className="label">Título eleitoral</label><input className="input" {...campo('titulo_eleitor')} /></div><div><label className="label">Nascimento</label><input type="date" className="input" {...campo('data_nascimento')} /></div><div><label className="label">Status</label><select className="input" {...campo('status_voto')}><option value="nao_identificado">Não identificado</option><option value="indeciso">Indeciso</option><option value="provavel">Provável</option><option value="confirmado">Confirmado</option><option value="oposicao">Oposição</option><option value="abstencao">Abstenção</option></select></div><div><label className="label">Telefone</label><input className="input" {...campo('telefone')} /></div><div><label className="label">WhatsApp</label><input className="input" {...campo('whatsapp')} /></div><div><label className="label">E-mail</label><input type="email" className="input" {...campo('email')} /></div><div className="sm:col-span-2"><label className="label">Endereço</label><input className="input" {...campo('endereco')} /></div><div><label className="label">Bairro</label><input className="input" {...campo('bairro')} /></div><div><label className="label">Cidade</label><input className="input" {...campo('cidade')} /></div><div><label className="label">UF</label><input className="input" maxLength="2" {...campo('uf')} /></div><div><label className="label">CEP</label><input className="input" {...campo('cep')} /></div><div><label className="label">Zona</label><input type="number" className="input" {...campo('zona_eleitoral')} /></div><div><label className="label">Seção</label><input type="number" className="input" {...campo('secao_eleitoral')} /></div><div className="sm:col-span-2 lg:col-span-3"><label className="label">Observações</label><textarea className="input min-h-20" {...campo('observacoes')} /></div></div>
 <div className="flex justify-between gap-3 mt-6">{eleitor&&podeExcluir?<button type="button" className="btn-secondary text-red-700" onClick={excluir}>Excluir</button>:<span/>}<div className="flex gap-2"><button type="button" className="btn-secondary" onClick={onFechar}>Cancelar</button><button className="btn-primary" disabled={salvando}>{salvando?'Salvando...':'Salvar'}</button></div></div></form></div>;
}
