import React, { useCallback, useEffect, useState } from 'react';
import { apiPost, apiRequest } from '../utils/api.js';
import { obterUsuario } from '../utils/authStorage.js';
import { AlertBox } from '../components/ui/ExecutiveUI.jsx';

const INICIAL={titulo:'',descricao:'',categoria:'',prioridade:'media',bairro:'',endereco_referencia:'',data_prazo:''};
export default function Demandas(){
 const usuario=obterUsuario(); const podeEditar=usuario?.nivel!=='visualizador';
 const [dados,setDados]=useState([]);const [form,setForm]=useState(INICIAL);const [aberto,setAberto]=useState(false);const [erro,setErro]=useState('');const [filtro,setFiltro]=useState('');
 const carregar=useCallback(async()=>{try{const d=await apiRequest('/demands?limit=100'+(filtro?'&status='+filtro:''));setDados(d.dados||[]);setErro('');}catch(e){setErro(e.message);}},[filtro]);
 useEffect(()=>{carregar();},[carregar]);
 async function criar(e){e.preventDefault();try{await apiPost('/demands',form);setForm(INICIAL);setAberto(false);carregar();}catch(err){setErro(err.message);}}
 async function status(id,valor){try{await apiRequest('/demands/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:valor})});carregar();}catch(e){setErro(e.message);}}
 return <div className="p-6 lg:p-8 max-w-6xl mx-auto"><header className="flex justify-between gap-4 mb-6"><div><h1 className="page-title">Demandas comunitárias</h1><p className="page-subtitle">Ouvidoria e acompanhamento de solicitações.</p></div>{podeEditar&&<button className="btn-primary" onClick={()=>setAberto(!aberto)}>Nova demanda</button>}</header>
 {erro&&<AlertBox tipo="erro">{erro}</AlertBox>}
 {aberto&&<form onSubmit={criar} className="card p-5 grid md:grid-cols-2 gap-3 mb-6"><div><label className="label">Título</label><input className="input" value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} required /></div><div><label className="label">Categoria</label><input className="input" value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})} /></div><div className="md:col-span-2"><label className="label">Descrição</label><textarea className="input min-h-24" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} required /></div><div><label className="label">Prioridade</label><select className="input" value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></div><div><label className="label">Prazo</label><input type="date" className="input" value={form.data_prazo} onChange={e=>setForm({...form,data_prazo:e.target.value})} /></div><div><label className="label">Bairro</label><input className="input" value={form.bairro} onChange={e=>setForm({...form,bairro:e.target.value})} /></div><div><label className="label">Referência</label><input className="input" value={form.endereco_referencia} onChange={e=>setForm({...form,endereco_referencia:e.target.value})} /></div><div className="md:col-span-2 flex gap-2 justify-end"><button type="button" className="btn-secondary" onClick={()=>setAberto(false)}>Cancelar</button><button className="btn-primary">Salvar demanda</button></div></form>}
 <div className="card p-4 mb-4 max-w-xs"><label className="label">Filtrar por status</label><select className="input" value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todos</option><option value="aberta">Aberta</option><option value="em_analise">Em análise</option><option value="em_andamento">Em andamento</option><option value="resolvida">Resolvida</option><option value="cancelada">Cancelada</option></select></div>
 <div className="card overflow-x-auto"><table className="gov-table"><thead><tr><th>Título</th><th>Categoria</th><th>Bairro</th><th>Prioridade</th><th>Status</th><th>Prazo</th></tr></thead><tbody>{dados.map(d=><tr key={d.id}><td><strong>{d.titulo}</strong><div className="text-xs text-slate-400 max-w-xs">{d.descricao}</div></td><td>{d.categoria||'—'}</td><td>{d.bairro||'—'}</td><td>{d.prioridade}</td><td>{podeEditar?<select className="input min-w-40" value={d.status} onChange={e=>status(d.id,e.target.value)}><option value="aberta">Aberta</option><option value="em_analise">Em análise</option><option value="em_andamento">Em andamento</option><option value="resolvida">Resolvida</option><option value="cancelada">Cancelada</option></select>:d.status}</td><td>{d.data_prazo?new Date(d.data_prazo).toLocaleDateString('pt-BR'):'—'}</td></tr>)}{!dados.length&&<tr><td colSpan="6" className="text-center py-10 text-slate-400">Nenhuma demanda cadastrada.</td></tr>}</tbody></table></div>
 </div>;
}
